import assert from 'node:assert/strict';
import http from 'node:http';
import {callTool,browser,mcpToolResult} from './server.mjs';
const checks=[];
const check=name=>{checks.push(name);console.log('PASS '+name);};
const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'text/html;charset=utf-8'});res.end('<!doctype html><title>State fixture</title><label>Name<input id="name"></label><button id="go">Apply</button><output>waiting</output><script>window.count=0;document.querySelector("button").onclick=()=>{window.count++;document.querySelector("output").textContent="Hello "+document.querySelector("input").value};</script>');});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const idx=(state,text)=>{const line=state.accessibility.tree.split('\n').find(line=>line.includes(text));assert(line,`${text} missing: ${state.accessibility.tree}`);return Number(line.match(/\[(\d+)\]/)[1]);};
try {
  await callTool('browser_launch',{url:`http://127.0.0.1:${server.address().port}`});
  await callTool('wait_for',{text:'Apply'});
  let state=await callTool('get_state',{include_text:true,include_screenshot:true});
  assert(state.accessibility && state.screenshots.length===1);
  const original=state.stateId;
  let result=await callTool('ax_set_value',{element_index:idx(state,'textbox "Name"'),value:'连续🙂'});
  state=result.state;
  assert(state.stateId!==original && state.accessibility.tree.includes('连续🙂'));
  assert(!result.requiresReobserve && result.verification.outcomeVerified===false);
  check('legacy arguments produce actual read-back with fresh post-action state');
  const mcp=mcpToolResult('ax_set_value',result);
  assert.equal(mcp.content.filter(c=>c.type==='image').length,1);
  assert(!('data' in mcp.structuredContent.state.screenshots[0]));
  check('nested screenshot is one MCP image without duplicate base64');
  await assert.rejects(callTool('ax_click',{element_index:idx(state,'button "Apply"')}),/stateId/);
  await assert.rejects(callTool('ax_click',{element_index:idx(state,'button "Apply"'),state_id:original}),/stateId/);
  assert.equal(await browser.evaluate({expression:'window.count'}),0);
  check('old indices and stale token rejected before click');
  result=await callTool('ax_click',{element_index:idx(state,'button "Apply"'),state_id:state.stateId});
  assert(result.state.accessibility.tree.includes('Hello 连续🙂'));
  check('token-authorized action returns verified application text');
  const getState=browser.getState.bind(browser);
  browser.getState=async()=>{throw new Error('synthetic observation failure');};
  result=await callTool('ax_click',{element_index:idx(result.state,'button "Apply"'),state_id:result.state.stateId});
  browser.getState=getState;
  assert(result.ok && result.requiresReobserve && result.observationError);
  assert.equal(await browser.evaluate({expression:'window.count'}),2);
  assert.equal(browser.axState,null);
  check('observation failure keeps dispatched action and never retries');
  state=await callTool('get_state',{});
  result=await callTool('ax_set_value',{element_index:idx(state,'textbox "Name"'),value:'optout',include_state:false});
  assert(result.requiresReobserve && !result.state && !browser.axState);
  check('opt-out preserves explicit observation workflow');
  const axGet=browser.axGet.bind(browser);
  browser.axGet=async()=>{throw new Error('AX must not run');};
  state=await callTool('get_state',{include_text:false,include_screenshot:true});
  browser.axGet=axGet;
  assert.equal(state.accessibility,null);assert(state.screenshots.length===1);
  check('visual-only observation skips accessibility scan');
  state=await callTool('get_state',{});
  const oldState=state.stateId;
  await browser.tabNew({url:'about:blank'});
  await assert.rejects(callTool('ax_click',{element_index:0,state_id:oldState}),/stale/);
  check('state token cannot cross tab boundaries');
  console.log(JSON.stringify({ok:true,checks:checks.length,passed:checks},null,2));
} finally {await browser.close();await new Promise(r=>server.close(r));}
